name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set image tag
        id: set_tag
        run: |
          IMAGE_TAG=outreach:${{ github.sha }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_B64 }}'
          credentials_json_format: 'base64'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          IMAGE=us-east1-docker.pkg.dev/jobsity-microservices-demo/my-docker-repo/$IMAGE_TAG
          docker build -t $IMAGE .
          docker push $IMAGE

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Write GCP credentials to file
        run: |
          printf '%s' "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d > gcp-key.json

      - name: Terraform Init
        working-directory: infra/staging
        run: |
          terraform init \
            -backend-config="bucket=outreach-terraform-state" \
            -backend-config="prefix=cloud-run-demo"

      - name: Terraform Apply
        working-directory: infra/staging
        run: |
          terraform apply -auto-approve \
            -var="gcp_credentials_file=${{ github.workspace }}/gcp-key.json" \
            -var="project_id=jobsity-microservices-demo" \
            -var="region=us-east1" \
            -var="docker_image=us-east1-docker.pkg.dev/jobsity-microservices-demo/my-docker-repo/${{ needs.docker-build-push.outputs.image_tag }}"
